/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pemrograman_visual;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import connect.Koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Anditeguh
 */
public class TeguhPrasetyo_201843500330 extends javax.swing.JFrame {
     private DefaultTableModel DftTblModel_member;
    private String SQL;
    ResultSet rs = null;
    

    /**
     * Creates new form TeguhPrasetyo_201843500330
     */
    public TeguhPrasetyo_201843500330() {
        initComponents();
//        this.cariData(SQL);
        this.TampilData();
        this.Update_table();
        
        try{
            int kode = 001;
            String str1 = String.valueOf(kode);
//            txt_kode.setText(str1);
            Connection con = connect.Koneksi.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(kode) from mobil");
            while(rs.next()){
                kode = rs.getInt(1);
                kode = kode+1;
                String str = String.valueOf(kode);
//                txt_kode.setText(str1);    
            }
            Update_table();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_biaya_sewa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_status = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_keterangan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mobil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setForeground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Kode");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel3.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Nama");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel3.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Tahun");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel3.add(txt_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Biaya Sewa/hari");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(txt_biaya_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Status");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txt_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia" }));
        jPanel3.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Keterangan(Warna, No Polisi,dsb)");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));
        jPanel3.add(txt_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 390, 200));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 900, 250));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UTS PEMROGRAMAN VISUAL");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teguh Prasetyo 201843500330");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 230, 80));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA MOBIL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 30));

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 90, 40));

        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 90, 40));

        jButton4.setText("CLEAR");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 90, 40));

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, 40));

        jButton5.setText("EXIT");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 90, 40));

        jPanel4.setBackground(new java.awt.Color(204, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Kata Kunci");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, -1, -1));
        jPanel4.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 560, 30));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 900, 50));

        table_mobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Tahun", "Biaya Sewa", "Status", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mobil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 900, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/car.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        String nama = txt_nama.getText();
        String tahun = txt_tahun.getText();
        String biaya = txt_nama.getText();
        String status = (String) txt_status.getSelectedItem();
        String keterangan = txt_keterangan.getText();
        
        try {
            Connection conn = Koneksi.getCon();
            PreparedStatement stmt = conn.prepareStatement("insert into mobil values(?,?,?,?,?,?)");
            stmt.setString(1, kode);
            stmt.setString(2, nama);
            stmt.setString(3, tahun);
            stmt.setString(4, biaya);
            stmt.setString(5, status);
            stmt.setString(6, keterangan);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);  
            new TeguhPrasetyo_201843500330().setVisible(true);
            TampilData();
            Update_table();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void table_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mobilMouseClicked
        // TODO add your handling code here:
            // menampilkan data kedalam form pengisian:
        int baris = table_mobil.rowAtPoint(evt.getPoint());
        String kode = table_mobil.getValueAt(baris, 0).toString();
        txt_kode.setText(kode);
        
        String nama =table_mobil.getValueAt(baris, 1).toString();
        txt_nama.setText(nama);
        
        String tahun =table_mobil.getValueAt(baris, 2).toString();
        txt_tahun.setText(tahun);
        
        String biaya =table_mobil.getValueAt(baris, 3).toString();
        txt_biaya_sewa.setText(biaya);
       
        String status = table_mobil.getValueAt(baris, 4).toString();
        txt_status.setSelectedItem(status);
        
        String keterangan = table_mobil.getValueAt(baris, 5).toString();
        txt_keterangan.setText(keterangan);
    }//GEN-LAST:event_table_mobilMouseClicked

    public void Update_table(){
        
        try{
               String sql = "select * from mobil";
                java.sql.Connection conn=(Connection)connect.Koneksi.getCon();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                rs = pst.executeQuery();
                table_mobil.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e){
            
        }
    }
    
    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
           try {
          Connection conn = Koneksi.getCon();
            PreparedStatement stmt = conn.prepareStatement("update mobil set nama=?,"
                    + " tahun=?, biaya_sewa=?, status=?, keterangan=? where kode=?");
             stmt.setString(1, txt_kode.getText());
            stmt.setString(2, txt_nama.getText());
            stmt.setString(3, txt_tahun.getText());
            stmt.setString(4, txt_biaya_sewa.getText());
            stmt.setString(5, (String) txt_status.getSelectedItem());
            stmt.setString(6, txt_keterangan.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
            Update_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from mobil where kode='"+txt_kode.getText()+"'";
            java.sql.Connection conn=(Connection)connect.Koneksi.getCon();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
            Update_table();
//            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

     public void TampilData(){
        DftTblModel_member = new DefaultTableModel();
        DftTblModel_member.addColumn("KODE");
        DftTblModel_member.addColumn("Nama Mobil");
        DftTblModel_member.addColumn("Tahun");
        DftTblModel_member.addColumn("Biaya Sewa");
        DftTblModel_member.addColumn("Status");
        DftTblModel_member.addColumn("Keterangan");
        table_mobil.setModel(DftTblModel_member);
        Connection conn = connect.Koneksi.getCon();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from mobil";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_member.addRow(new Object[]{
                    res.getString("kode"),
                    res.getString("nama"),
                    res.getString("tahun"),
                    res.getString("biaya_sewa"),
                    res.getString("status"),
                    res.getString("keterangan")
                        
                });
            }
             Update_table();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeguhPrasetyo_201843500330.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeguhPrasetyo_201843500330.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeguhPrasetyo_201843500330.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeguhPrasetyo_201843500330.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeguhPrasetyo_201843500330().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_mobil;
    private javax.swing.JTextField txt_biaya_sewa;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_keterangan;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JComboBox<String> txt_status;
    private javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables
}
